### ISSUE TITLE
Double click doesn't go to/exit fullscreen anymore

### ISSUE THREAD

**Issue by elmagio** [gnome-mpv/gnome-mpv#179]
Overview Description:

You can still reach fullscreen with "f11" and exit it with "escape", or through the GUI, but double click doesn't do it anymore.

Steps to Reproduce:
1. Open a video
2. Double click anywhere on the window

Actual Results: Nothing happens.

Expected Results: The player goes to fullscreen.

Version: 0.9

Additional Information: Ubuntu 16.04, Gnome-Shell 3.18.

**Comment by gnome-mpv** [comment]
What version of mpv are you using?

**Comment by region51** [comment]
F23
```
[maxim@localhost ~]$ rpm -q gnome-mpv mpv-libs
gnome-mpv-0.9-1.fc23.R.x86_64
mpv-libs-0.17.0-1.fc23.R.x86_64
```
double click fs working.

**Comment by elmagio** [comment]
I'm using mpv 0.14. I believe it's the one that ships in Ubuntu 16.04 repositories.

But wouldn't it have more to do with the frontend that is gnome-mpv?

**Comment by gnome-mpv** [comment]
gnome-mpv now requires mpv >= 0.17 to work properly. In older versions of mpv, the `mouse` input command doesn't work when mpv's input cursor handling is disabled. gnome-mpv used to work around this by handling mouse events itself. Later this bug was fixed, so now gnome-mpv just sends mouse events to mpv. This also allows mouse bindings in `input.conf` to work properly as well. However, if your mpv is older than 0.17, mouse bindings would simply not work at all.

For Ubuntu 16.04, you can use this [PPA](https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests) to get mpv 0.17.

**Comment by elmagio** [comment]
Just installed mpv 0.17 through that PPA, and double-click to fullscreen still doesn't work on gnome-mpv.

Should I add something to input.conf to make it work? And also would that need to be added to mpv's system wide input.conf or the one I made for gnome-mpv?

**Comment by gnome-mpv** [comment]
It should just work OOTB. Can you run gnome-mpv in terminal like this `G_MESSAGES_DEBUG=all gnome-mpv`, try double-clicking to fullscreen, and post the log messages here?

**Comment by elmagio** [comment]
The output for the first thing was: 

> ** (gnome-mpv:26683): DEBUG: Sent single button 0 click at 470x471 to mpv
** (gnome-mpv:26683): DEBUG: Sent single button 0 click at 470x471 to mpv
** (gnome-mpv:26683): DEBUG: Sent double button 0 click at 470x471 to mpv

For each double click.

And for the second thing, it said 0.14.0 instead, even though I upgraded it, so I guess that's the issue.

**Comment by gnome-mpv** [comment]
It might help to uninstall mpv 0.14 before installing mpv 0.17 from the PPA.

**Comment by elmagio** [comment]
I thought that might be it too, so I uninstalled both mpv and gnome-mpv then reinstalled them, with the same results.

**Comment by elmagio** [comment]
Just noticed that among the dependencies for gnome-mpv from [this ppa](https://launchpad.net/~xuzhen666/+archive/ubuntu/gnome-mpv), there is a "libmpv1" package, and that one is in version 0.14.

So is that an issue with this ppa?

**Comment by elmagio** [comment]
It seemed like it was an issue with said PPA.

I removed it and added [this one](https://launchpad.net/~mc3man/+archive/ubuntu/xerus-media) instead, as it included libmpv as well as gnome-mpv, and now everything works. Note that having mpv 0.14 isn't necessary if libmpv 0.17 is installed, as libmpv seems to be prioritized by gnome-mpv, at least in the versions provided on those PPAs.

**Comment by gnome-mpv** [comment]
You're welcome.
