### ISSUE TITLE
Icon is wrong under KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [gnome-mpv/gnome-mpv#341]
Overview Description:
A Wayland generic icon appears in Plasma panel.

Steps to Reproduce:
1. start kde plasma wayland session
2. open gnome-mpv
3.

Actual Results:
A Wayland generic icon appears in Plasma panel. See screenshot.
![gnome-mpv](https://user-images.githubusercontent.com/15967631/35981212-dc2bb30c-0cd3-11e8-9d1c-4f6df058524b.png)

Expected Results:
Gnome-mpv icon appears in Plasma panel.
Version:
0.13

Additional Information:
My gnome-mpv was installed via flatpak.

**Comment by TingPing** [comment]
Flatpak bug, I'll fix it shortly.

@gnome-mpv would you be ok with renaming all icons here to use the `io.github.GnomeMpv` prefix? (That is required with Flatpak and the rename is causing this issue)

**Comment by gnome-mpv** [comment]
> @gnome-mpv would you be ok with renaming all icons here to use the io.github.GnomeMpv prefix? (That is required with Flatpak and the rename is causing this issue)

Yes, I'm okay with that.

**Comment by gnome-mpv** [comment]
ae0d35074d2493865e7327e1ace7dac27b02f0d3

**Comment by TingPing** [comment]
@gnome-mpv A new release would be appreciated btw.

**Comment by gnome-mpv** [comment]
> A new release would be appreciated btw. (don't forget to bump appstream this time)

@TingPing Does [this](https://github.com/gnome-mpv/gnome-mpv/commit/0e178f1a35f396b2999fba3e4ee6c7f23c068cde) look good?

**Comment by TingPing** [comment]
@gnome-mpv Yup

**Comment by gnome-mpv** [comment]
@TingPing I'll merge that to master and make a new release in about a week or so if there are no new bugs.

**Comment by glaubersm** [comment]
not fixed in 0.14.

**Comment by TingPing** [comment]
Hmm, well it could be a bug anywhere between Gtk and Plasma. I'm 99% sure all the app should be doing is calling `gtk_window_set_default_icon_name()` as it does and the icon is there now.

**Comment by glaubersm** [comment]
I have the following GTK3 apps installed via flatpak and running natively under Wayland:
gnome-mpv
pitivi
lollypop
ciano

gnome-mpv is the only that shows Wayland generic icon in kde plasma panel (and in alt+tab menu).
pitivi and lollypop: icon ok in plasma panel, wrong in alt+tab.
ciano: icon ok in both kde plasma panel and alt+tab menu.

**Comment by TingPing** [comment]
@glaubersm As an experiment (and something that should be done anyway), I've pushed [an update](https://flathub.org/builds/#/builders/1/builds/2257) that installs 64/128 sized pngs, try again in an hour or so when the update comes.

**Comment by TingPing** [comment]
@glaubersm There is a chance #346 is relevant also.

**Comment by glaubersm** [comment]
unfortunately icon is still wrong after the update.

**Comment by TingPing** [comment]
One thing to look for in those apps you listed is if they set the icon by *name* or directly.

**Comment by glaubersm** [comment]
I have just updated to 0.15 on Arch Linux via flathub. Now the icon is correct in plasma panel (bar on bottom), but it's still wrong in task switcher (alt+tab).
